/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./KogenFactory.types";
import * as _1 from "./KogenFactory.client";
import * as _2 from "./KogenFactory.react-query";
import * as _3 from "./KogenMarkets.types";
import * as _4 from "./KogenMarkets.client";
import * as _5 from "./KogenMarkets.react-query";
export const KogenFactory = { ..._0, ..._1, ..._2 };
export const KogenMarkets = { ..._3, ..._4, ..._5 };
