/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./KogenMarkets.types";
import * as _1 from "./KogenMarkets.client";
import * as _2 from "./KogenMarkets.react-query";
export namespace contracts {
  export const KogenMarkets = { ..._0, ..._1, ..._2 };
}
