/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export type Addr = string;
export interface InstantiateMsg {
  base_decimals?: number | null;
  base_denom: string;
  expiry: Timestamp;
  min_order_quantity: Uint128;
  owner: Addr;
  quote_decimals?: number | null;
  quote_denom: string;
  strike_price: Uint128;
}
export type ExecuteMsg =
  | {
      update_config: {};
    }
  | {
      ask_order: {
        price: Uint128;
        quantity: Uint128;
      };
    }
  | {
      bid_order: {
        price: Uint128;
        quantity: Uint128;
      };
    };
export type QueryMsg =
  | {
      config: {};
    }
  | {
      bids: {
        price?: Uint128 | null;
      };
    }
  | {
      asks: {
        price?: Uint128 | null;
      };
    }
  | {
      locked_amount: {
        owner: Addr;
      };
    }
  | {
      position: {
        owner: Addr;
      };
    };
export type ArrayOfOrdersResponse = OrdersResponse[];
export interface OrdersResponse {
  orders: OrderBookItem[];
  price: Uint128;
}
export interface OrderBookItem {
  owner: Addr;
  quantity_in_base: Uint128;
}
export interface Config {
  base_decimals: number;
  base_denom: string;
  expiry: Timestamp;
  instantiated: Timestamp;
  min_order_quantity_in_base: Uint128;
  owner: Addr;
  quote_decimals: number;
  quote_denom: string;
  strike_price_in_quote: Uint128;
}
export interface LockedAmountResponse {
  locked_base_denom: Uint128;
  locked_quote_denom: Uint128;
}
export interface PositionResponse {
  position_in_base: number;
}
